[project]
name = "shopee-product-quantity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "natsort>=8.4.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "rich>=14.0.0",
    "unidecode>=1.4.0",
]
